#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🛠️ Running Biome Auto-fix (Lint & Format)..."
# Tự động sửa lỗi Lint & Format code
npm run lint

echo "🔎 Running type-check..."
# Kiểm tra Type (TypeScript)
npm run typecheck
